### ISSUE TITLE
Dockerfile would be awesome. 

### ISSUE THREAD

**Issue by onexbash** [RiskyMH/Email#2]
We all love containers. You as well @RiskyMH 😄 .

If nothing speaks against it I can set it up and create a Pull Request.

**Comment by RiskyMH** [comment]
Currently I don't think its that necessary, but maybe if it gets more complicated than a basic Next.JS app this can be looked at again!

**Comment by RiskyMH** [comment]
Done in dcecd072062ef03516f300ef9f135bb067e7f2cc
